services:
  session-store:
    container_name: session-store
    image: redis:7.2.5
    ports:
      - "6379:6379"

  db:
    container_name: db
    image: postgres:16.3
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_DB=library_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  service-auth:
    container_name: service-auth
    build: ./service-auth
    depends_on:
      session-store:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://session-store:6379/0
      - DATABASE_URL=postgresql+psycopg2://postgres:S3cret@db:5432/library_db

  service-user:
    container_name: service-user
    build: ./service-user
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:S3cret@db:5432/library_db

  service-book:
    container_name: service-book
    build: ./service-book
    depends_on:
      session-store:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://session-store:6379/0
      - DATABASE_URL=postgresql+psycopg2://postgres:S3cret@db:5432/library_db

  api-gateway:
    container_name: api-gateway
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service-auth
      - service-user
      - service-book
